"""
Generate five PURITY mixed datasets tuned for the muon-decay tail-reveal study:
  1. tail_reveal_training            : mixed pie/michel (uses *_train unmixed parquets)
  2. tail_reveal_validation          : mixed pie/michel, same parameters as training (uses *_val)
  3. tail_reveal_michel_eval         : Michel-only, enforce_window=False
                                       (natural decay-time distribution; many positrons
                                        fall outside the readout window)
  4. tail_reveal_michel_eval_in_win  : Michel-only, enforce_window=True, max_reroll=5
                                       (oversamples in-window decays by rerolling sources)
  5. tail_reveal_pie_eval            : Pie-only (π → e ν), enforce_window=True
                                       (signal-positive population for ROC / acceptance
                                        plots — the events the tail-reveal classifier
                                        should KEEP, not reject)

Each mixer instance reuses the ROOT-derived parquets generated by
generate_unmixed.py. The eval splits are disjoint at the source-file level
from train/val splits, so benchmark numbers reflect held-out events.

Pile-up-mixer config blocks:
  - TRAIN_VAL_OPTS         : shared between training and validation
                             (max_reroll=3, cal_only_fraction=0.0)
  - BENCHMARK_OPTS_OPEN    : Michel eval with no window enforcement
  - BENCHMARK_OPTS_IN_WIN  : Michel eval with window enforcement and max_reroll=5
                             (also reused for pie_eval — pi-decay is prompt so
                              window enforcement is the natural choice)

Usage:
    python generate_tail_reveal.py                                  # all five
    python generate_tail_reveal.py --only training                  # one of:
                                                                    #   training | validation
                                                                    #   michel_eval | michel_eval_in_win
                                                                    #   pie_eval
"""
import argparse
import os
import sys

import pyarrow as pa
import pyarrow.parquet as pq

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from unified_reco.pileup_mixer import PileupMixer

DATA_DIR = "/mnt/c/Users/obbee/research/notebooks/ML/data/purity"
RECO_DIR = os.path.dirname(os.path.abspath(__file__))

# Per-split unmixed parquets produced by generate_unmixed.py
SPLIT_FILES = {
    "train": dict(
        michel=os.path.join(DATA_DIR, "unmixed_michel_train.parquet"),
        pie   =os.path.join(DATA_DIR, "unmixed_pie_train.parquet"),
    ),
    "val": dict(
        michel=os.path.join(DATA_DIR, "unmixed_michel_val.parquet"),
        pie   =os.path.join(DATA_DIR, "unmixed_pie_val.parquet"),
    ),
    "eval": dict(
        michel=os.path.join(DATA_DIR, "unmixed_michel_eval.parquet"),
        pie   =os.path.join(DATA_DIR, "unmixed_pie_eval.parquet"),
    ),
}

# Pileup-mixer settings shared by training and validation (the two 'mixed' jobs).
TRAIN_VAL_OPTS = dict(
    biased_fraction=0.0,
    biased_sigma=2.0,
    cal_only_fraction=0.0,
    radio_rate=2e7,
    enforce_window=True,     # retry until primary positron survives the readout window
    trigger_gap_ns=2.0,
    pie_mix_fraction=0.1,    # 80% michel / 20% pie — oversample hard michel events
    max_reroll=3,
)

# Michel eval, no window enforcement — natural decay-time distribution including
# the long tail where the positron falls outside the readout window.
BENCHMARK_OPTS_OPEN = dict(
    biased_fraction=0.0,
    biased_sigma=2.0,
    cal_only_fraction=0.0,
    radio_rate=2e7,
    enforce_window=False,
    trigger_gap_ns=2.0,
)

# Michel eval, with window enforcement and a higher reroll cap so we oversample
# decays that DID land inside the window.
BENCHMARK_OPTS_IN_WIN = dict(
    biased_fraction=0.0,
    biased_sigma=2.0,
    cal_only_fraction=0.0,
    radio_rate=2e7,
    enforce_window=True,
    trigger_gap_ns=2.0,
    max_reroll=5,
)


def _job_specs(args):
    """Build the job specifications using CLI-controlled event counts."""
    return {
        "training": dict(
            split="train",
            mode="mixed",
            num_events=args.num_train,
            opts=TRAIN_VAL_OPTS,
            out=os.path.join(RECO_DIR, "tail_reveal_training", "data.parquet"),
        ),
        "validation": dict(
            split="val",
            mode="mixed",
            num_events=args.num_val,
            opts=TRAIN_VAL_OPTS,
            out=os.path.join(RECO_DIR, "tail_reveal_validation", "data.parquet"),
        ),
        "michel_eval": dict(
            split="eval",
            mode="michel",
            num_events=args.num_eval,
            opts=BENCHMARK_OPTS_OPEN,
            out=os.path.join(RECO_DIR, "tail_reveal_michel_eval", "data.parquet"),
        ),
        "michel_eval_in_win": dict(
            split="eval",
            mode="michel",
            num_events=args.num_eval,
            opts=BENCHMARK_OPTS_IN_WIN,
            out=os.path.join(RECO_DIR, "tail_reveal_michel_eval_in_win", "data.parquet"),
        ),
        # Pie-only eval: pi → e ν events, no Michel chain. Needed as the
        # "signal positive" population for any tail-reveal classifier ROC
        # / acceptance plot. enforce_window=True since pi-decay positrons
        # are prompt and well-localized in time; tail-reveal rejection of
        # them is the false-negative axis of the comparison.
        "pie_eval": dict(
            split="eval",
            mode="pie",
            num_events=args.num_eval,
            opts=BENCHMARK_OPTS_IN_WIN,
            out=os.path.join(RECO_DIR, "tail_reveal_pie_eval", "data.parquet"),
        ),
    }


def run_job(mixer, name, spec, chunk_size=100_000):
    """Generate `spec['num_events']` events in `chunk_size`-row pieces and
    append each as a row-group to a single parquet file. Bounds peak RAM to
    roughly the cost of one chunk (DataFrame + transient pyarrow Table)."""
    out = spec["out"]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    n_total = spec["num_events"]

    print(f"\n=== [{name}] split={spec['split']} mode={spec['mode']} "
          f"n={n_total}  chunk={chunk_size}  -> {out}", flush=True)

    writer = None
    schema = None
    n_done = 0
    while n_done < n_total:
        n_chunk = min(chunk_size, n_total - n_done)
        df = mixer.generate_batch(n_chunk, mode=spec["mode"], **spec["opts"])
        table = pa.Table.from_pandas(df)

        if writer is None:
            schema = table.schema
            writer = pq.ParquetWriter(out, schema)
        else:
            # Force schema match in case pyarrow infers slightly different
            # types between chunks (e.g. empty arrays in some rows).
            table = table.cast(schema, safe=False)

        writer.write_table(table)
        n_done += len(df)
        del df, table          # release peak RAM before the next chunk
        print(f"    [{name}] {n_done}/{n_total}", flush=True)

    if writer is not None:
        writer.close()
    print(f"    wrote {n_done} rows to {out}", flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--only",
                        choices=["training", "validation",
                                 "michel_eval", "michel_eval_in_win",
                                 "pie_eval"],
                        default=None,
                        help="Run a single job instead of all five.")
    parser.add_argument("--num_train", type=int, default=200_000)
    parser.add_argument("--num_val",   type=int, default=20_000)
    parser.add_argument("--num_eval",  type=int, default=100_000)
    parser.add_argument("--chunk_size", type=int, default=100_000,
                        help="Events per parquet row-group; controls peak RAM.")
    args = parser.parse_args()

    specs = _job_specs(args)
    selected = [args.only] if args.only else list(specs.keys())

    # Group jobs by source split so we instantiate one PileupMixer per split.
    by_split = {}
    for name in selected:
        by_split.setdefault(specs[name]["split"], []).append(name)

    for split, names in by_split.items():
        files = SPLIT_FILES[split]
        for p in (files["michel"], files["pie"]):
            if not os.path.exists(p):
                raise FileNotFoundError(
                    f"Missing unmixed parquet for split '{split}': {p}\n"
                    f"Run generate_unmixed.py first."
                )
        print(f"\n--- Loading PileupMixer for split={split} "
              f"(michel={files['michel']}, pie={files['pie']})", flush=True)
        mixer = PileupMixer(michel_path=files["michel"], pie_path=files["pie"])
        for name in names:
            run_job(mixer, name, specs[name], chunk_size=args.chunk_size)


if __name__ == "__main__":
    main()
